server:
  port: 80
spring:
  main:
      allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aksham_nur
    username: postgres
    password: yusufbek200

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  access:
    key: eaklnflAKklSNAEFml
    expiration-time: 10000
  refresh:
    key: ask;gnaeslk/g;mae;fl
    expiration-time: 10000